language: node_js
node_js: '5.3'
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
script:
  - gulp test:travis
after_success:
  - gulp test:coveralls
env:
  - CXX=g++-4.8
